sudo: required
services:
  -docker

before_install:
  - docker build -t irfanvox/docker-react -f Dockerfile.dev .

script:
  - docker run irfanvox/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-067437736266"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: AKIAQ7M42GFFO3RUEJ6J
  secret_access_key:
    secure: "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"
